language: python
python:
  - 2.7
  - 3.4
before_install:
  - sudo apt-get update
  - git clone --recursive https://github.com/ipython/ipython.git
install:
  - sudo apt-get install pandoc libzmq3-dev
  - cd ipython && pip install -e ".[notebook]" && cd ..
  - pip install nose
script:
  - nosetests
