language: python
python:
  - 2.7
  - 3.4
sudo: false
branches:
  only:
    - master
env:
  matrix:
    - GROUP=docs
    - GROUP=
  global:
    - secure: Ry2LhsYWOtVppoorTkOXyL6C6cEMw1bfqsHDka76kNSQzkn1HOpFOnVzjQk3kW3QxP9N60vcPlMtMln1jW1tsQRkh2mPT3EI0ugX18R5btR9R69CZSVo0At666HuQeZ6WN/a+pKWpaHYSFlXvSvlkLXkfW++AXbkShWvkD6Z0Hg=
before_install:
  - cd ~ && git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels && cd -
  - cd ~ && git clone --recursive https://github.com/ipython/ipython.git && cd -
install:
  - cd ~/ipython && git checkout a4950d68199a4ccdf4ff23c5bb8b51cc7faaad7a && pip install -f ~/travis-wheels/wheelhouse file://$PWD#egg=ipython[all] && cd -
  - pip install -r requirements.txt
  - pip install nose coverage coveralls requests!=2.4.2 invoke
  - if [[ $GROUP == 'docs' ]]; then python setup.py install; else pip install -e .; fi
  - python setup.py install
  - cp nbextensions/* $(ipython locate)/nbextensions/
script:
  - invoke tests --group="${GROUP}" --python-version="${TRAVIS_PYTHON_VERSION}" --pull-request="${TRAVIS_PULL_REQUEST}" --github-token="${GH_TOKEN}" --git-name="${GIT_NAME}" --git-email="${GIT_EMAIL}"
after_success:
  - invoke after_success --group="${GROUP}" --python-version="${TRAVIS_PYTHON_VERSION}"
