language: python
python:
  - 2.7
  - 3.4
branches:
  only:
    - master
env:
  matrix:
    - GROUP=docs
    - GROUP=js
    - GROUP=python
addons:
  apt:
    packages:
    - pandoc
before_install:
  - pip install invoke
  - invoke before_install --group="$GROUP" --python-version="$TRAVIS_PYTHON_VERSION"
install:
  - if [[ $GROUP == 'docs' ]]; then python setup.py install; else pip install -e .; fi
script:
  - invoke tests --group="$GROUP"
after_success:
  - invoke after_success --group="$GROUP"
