language: python
python:
  - 2.7
  - 3.4
env:
  - GROUP=js
  - GROUP=
before_install:
  # Pierre Carrier's PPA for PhantomJS and CasperJS
  - time sudo add-apt-repository -y ppa:pcarrier/ppa
  - sudo apt-get update
  - git clone --recursive https://github.com/ipython/ipython.git
install:
  - sudo apt-get install pandoc casperjs libzmq3-dev
  # pin tornado < 4 for js tests while phantom is on super old webkit
  - if [[ $GROUP == 'js' ]]; then pip install 'tornado<4'; fi
  - cd ipython && pip install -e ".[notebook]" && cd ..
  - pip install nose
script:
  - ./scripts/runtests $GROUP
