language: python
python:
  - 2.7
  - 3.4
branches:
  only:
    - master
env:
  matrix:
    - GROUP=docs
    - GROUP=js
    - GROUP=
  global:
    - secure: "Z7rZ/XnMH3zJBIvUAnBsgz6vddTTs+HMpt6JzzqzqVxiAK0ulxoV9q5kFIn0vCVJ61lu8HaCFTN2StrPdIGvejbirdG8i4ZpBzzg4efD23FWDctA64tNtpr+WH3h3ZgdJr2mzEwloN3gd5M1EN8CTnpKUiYnx6Iw1j1+cFUhxfA="
before_install:
  # Pierre Carrier's PPA for PhantomJS and CasperJS
  - time sudo add-apt-repository -y ppa:pcarrier/ppa
  - sudo apt-get update
  - cd ~
  - git clone --recursive https://github.com/ipython/ipython.git
  - cd -
install:
  - sudo apt-get install pandoc casperjs libzmq3-dev
  # pin tornado < 4 for js tests while phantom is on super old webkit
  - if [[ $GROUP == 'js' ]]; then pip install 'tornado<4'; fi
  - cd ~/ipython && git submodule update && pip install -e ".[notebook]" && cd -
  - pip install -r requirements.txt
  - pip install nose coverage coveralls requests!=2.4.2 invoke
  - python setup.py install
  - if [[ $GROUP == 'js' ]]; then cp nbextensions/* $(ipython locate)/nbextensions/; fi
script:
  - invoke tests --group="${GROUP}" --python-version="${TRAVIS_PYTHON_VERSION}" --pull-request="${TRAVIS_PULL_REQUEST}" --github-token="${GH_TOKEN}" --git-name="${GIT_NAME}" --git-email="${GIT_EMAIL}"
after_success:  
  - invoke after_success --group="${GROUP}" --python-version="${TRAVIS_PYTHON_VERSION}" --pull-request="${TRAVIS_PULL_REQUEST}"
